### ISSUE TITLE
【建议提交】【1.4.2】【log4j的配置问题】

### ISSUE THREAD

**Issue by iblader** [BeardedManZhao/mathematical-expression#17]
我觉得是不是log4j的配置文件不应该直接使用root logger，而应该给项目专门的名称，否则这个配置有可能会覆盖其他使用本项目的log配置信息；或者干脆不要内嵌log4j的xml配置，由使用方自行配置。

**Comment by BeardedManZhao** [comment]
感谢您的反馈，这是一个非常重要的建议，我们决定采纳，并在更新日志中进行对您的反馈鸣谢！

**Comment by iblader** [comment]
感谢您的时间和采纳:P
